name: Deploy to production
on:
  workflow_run:
    workflows:
      - Unit Testing
    types:
      -completed
  push:
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          key: ${{ secrets.KEY }}
          script: ANSIBLE_BECOME_PASS=${{ secrets.PASS }} ansible-playbook ~/ansible/plays/deployFikaFinds.yaml --ask-become-pass

