name: Unit Testing
on: push

env:
  DOCKER_IMAGE_NAME: fikafinds

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup docker
        uses: docker/setup-push-action@v2
  
      - name: build image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha, mode=max

      - name: run tests in docker
        run: docker run ${{ env.DOCKER_IMAGE_NAME }}:latest npm test
